server:
  port: 8090

spring:
  application:
    name: Delta-Force

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.brenden.**.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0